name: EE6222
channels:
  - pytorch
  - defaults
dependencies:
  - python = 3.8.5
  - pip = 20.3
  - cudatoolkit = 11.3
  - pytorch = 1.12.1
  - torchvision = 0.13.1
  - numpy = 1.23.1 
  - pip:
    - opencv-python==4.6.0.66
    - scikit-learn
    - tqdm 
    - pandas
    - matplotlib
    - spicy
